apiVersion: v1
kind: Service
metadata:
  name: {{ include "nkepsx.fullname" . }}-orchestrator-svc
  labels:
    {{- include "nkepsx.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "nkepsx.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator