apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nkepsx.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  HUGGINGFACE_TOKEN: "{{ .Values.secrets.huggingfaceToken | default "" }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.secrets.awsAccessKeyId | default "" }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.secrets.awsSecretAccessKey | default "" }}"